/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentListeningRouteImport } from './routes/student.listening'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentListeningRoute = StudentListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parent': typeof ParentRoute
  '/student': typeof StudentRouteWithChildren
  '/student/listening': typeof StudentListeningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parent': typeof ParentRoute
  '/student': typeof StudentRouteWithChildren
  '/student/listening': typeof StudentListeningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parent': typeof ParentRoute
  '/student': typeof StudentRouteWithChildren
  '/student/listening': typeof StudentListeningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/parent' | '/student' | '/student/listening'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/parent' | '/student' | '/student/listening'
  id: '__root__' | '/' | '/parent' | '/student' | '/student/listening'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParentRoute: typeof ParentRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/listening': {
      id: '/student/listening'
      path: '/listening'
      fullPath: '/student/listening'
      preLoaderRoute: typeof StudentListeningRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentListeningRoute: typeof StudentListeningRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentListeningRoute: StudentListeningRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParentRoute: ParentRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
