/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentVocabularyRouteImport } from './routes/student.vocabulary'
import { Route as StudentListeningRouteImport } from './routes/student.listening'
import { Route as StudentVocabularyCategoryRouteImport } from './routes/student.vocabulary.$category'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentVocabularyRoute = StudentVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => StudentRoute,
} as any)
const StudentListeningRoute = StudentListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => StudentRoute,
} as any)
const StudentVocabularyCategoryRoute =
  StudentVocabularyCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => StudentVocabularyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parent': typeof ParentRoute
  '/student': typeof StudentRouteWithChildren
  '/student/listening': typeof StudentListeningRoute
  '/student/vocabulary': typeof StudentVocabularyRouteWithChildren
  '/student/vocabulary/$category': typeof StudentVocabularyCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parent': typeof ParentRoute
  '/student': typeof StudentRouteWithChildren
  '/student/listening': typeof StudentListeningRoute
  '/student/vocabulary': typeof StudentVocabularyRouteWithChildren
  '/student/vocabulary/$category': typeof StudentVocabularyCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parent': typeof ParentRoute
  '/student': typeof StudentRouteWithChildren
  '/student/listening': typeof StudentListeningRoute
  '/student/vocabulary': typeof StudentVocabularyRouteWithChildren
  '/student/vocabulary/$category': typeof StudentVocabularyCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parent'
    | '/student'
    | '/student/listening'
    | '/student/vocabulary'
    | '/student/vocabulary/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/parent'
    | '/student'
    | '/student/listening'
    | '/student/vocabulary'
    | '/student/vocabulary/$category'
  id:
    | '__root__'
    | '/'
    | '/parent'
    | '/student'
    | '/student/listening'
    | '/student/vocabulary'
    | '/student/vocabulary/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParentRoute: typeof ParentRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/vocabulary': {
      id: '/student/vocabulary'
      path: '/vocabulary'
      fullPath: '/student/vocabulary'
      preLoaderRoute: typeof StudentVocabularyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/listening': {
      id: '/student/listening'
      path: '/listening'
      fullPath: '/student/listening'
      preLoaderRoute: typeof StudentListeningRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/vocabulary/$category': {
      id: '/student/vocabulary/$category'
      path: '/$category'
      fullPath: '/student/vocabulary/$category'
      preLoaderRoute: typeof StudentVocabularyCategoryRouteImport
      parentRoute: typeof StudentVocabularyRoute
    }
  }
}

interface StudentVocabularyRouteChildren {
  StudentVocabularyCategoryRoute: typeof StudentVocabularyCategoryRoute
}

const StudentVocabularyRouteChildren: StudentVocabularyRouteChildren = {
  StudentVocabularyCategoryRoute: StudentVocabularyCategoryRoute,
}

const StudentVocabularyRouteWithChildren =
  StudentVocabularyRoute._addFileChildren(StudentVocabularyRouteChildren)

interface StudentRouteChildren {
  StudentListeningRoute: typeof StudentListeningRoute
  StudentVocabularyRoute: typeof StudentVocabularyRouteWithChildren
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentListeningRoute: StudentListeningRoute,
  StudentVocabularyRoute: StudentVocabularyRouteWithChildren,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParentRoute: ParentRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
